# Generated by Django 4.1.1 on 2024-05-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('sale', 'Bán'), ('rent', 'Cho thuê')], default='sale', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('apartment', 'Căn hộ chung cư'), ('detached', 'Nhà riêng'), ('villa', 'Biệt thự liền kề'), ('townhouse', 'Nhà mặt phố'), ('shophouse', 'Shophouse nhà phố thương mại'), ('land', 'Đất')], default='apartment', max_length=20),
        ),
    ]
