# Generated by Django 4.1.1 on 2024-05-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='product',
            name='area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
