# Generated by Django 4.1.1 on 2024-05-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('man', 'nam'), ('woman', 'nu')], default='man', max_length=50, null=True),
        ),
    ]
