# Generated by Django 4.1.1 on 2024-05-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_conplete_order_complete_alter_customer_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complete',
            new_name='conplete',
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('man', 'nam'), ('woman', 'nu')], default='man', max_length=50, null=True),
        ),
    ]
