# Generated by Django 4.1.1 on 2024-05-19 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_complete_order_conplete_alter_customer_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='conplete',
            new_name='complete',
        ),
    ]
