# Generated by Django 4.1.1 on 2024-06-19 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_category_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryForRent',
        ),
        migrations.CreateModel(
            name='CategoryForSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sub', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='app.categoryforsale')),
            ],
        ),
    ]
