# Generated by Django 4.1.1 on 2024-06-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_category_categoryforrent_categoryforsale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_for_rent',
        ),
        migrations.AddField(
            model_name='product',
            name='category_for_sale',
            field=models.ManyToManyField(related_name='product', to='app.categoryforsale'),
        ),
    ]
