# Generated by Django 4.1.1 on 2024-06-26 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
    ]
