# Generated by Django 4.1.1 on 2024-06-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
