# Generated by Django 4.1.1 on 2024-07-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
